export enum AccountRole {
  DEPARTMENT = "ROLE_DEPARTMENT",
  STAFF = "ROLE_STAFF",
  ADMIN = "ROLE_ADMIN",
  WAREHOUSE_MANAGER = "ROLE_WAREHOUSE_MANAGER",
  ACCOUNTING = "ROLE_ACCOUNTING",
}

export enum AccountRoleForRequest {
  DEPARTMENT = "DEPARTMENT",
  STAFF = "STAFF",
  ADMIN = "ADMIN",
  WAREHOUSE_MANAGER = "WAREHOUSE_MANAGER",
  ACCOUNTING = "ACCOUNTING",
}