export enum AccountRole {
    DEPARTMENT = "ROLE_DEPARTMENT",
    STAFF = "ROLE_STAFF",
    ADMIN = "ROLE_ADMIN",
    WAREHOUSE_MANAGER = "ROLE_WAREHOUSE_MANAGER",
    ACCOUNTING = "ROLE_ACCOUNTING",
}

export enum AccountRoleForRequest {
    DEPARTMENT = "DEPARTMENT",
    STAFF = "STAFF",
    ADMIN = "ADMIN",
    WAREHOUSE_MANAGER = "WAREHOUSE_MANAGER",
    ACCOUNTING = "ACCOUNTING",
}

export enum ImportStatus {
    NOT_STARTED = "NOT_STARTED",
    IN_PROGRESS = "IN_PROGRESS",
    COUNTED = "COUNTED",
    CONFIRMED = "CONFIRMED",
    COMPLETED = "COMPLETED",
    CANCELLED = "CANCELLED",
    EXTENDED = "EXTENDED",
}

export enum ExportStatus {
    NOT_STARTED = "NOT_STARTED",
    IN_PROGRESS = "IN_PROGRESS",
    COUNTED = "COUNTED",
    COUNT_CONFIRMED = "COUNT_CONFIRMED",
    WAITING_EXPORT = "WAITING_EXPORT",
    CONFIRMED = "CONFIRMED",
    COMPLETED = "COMPLETED",
    CANCELLED = "CANCELLED",
}

export enum DetailStatus {
    LACK = "LACK",
    EXCESS = "EXCESS",
    MATCH = "MATCH",
}