export enum AccountRole {
  DEPARTMENT = "ROLE_DEPARTMENT",
  STAFF = "ROLE_STAFF",
  ADMIN = "ROLE_ADMIN",
  WAREHOUSE_MANAGER = "ROLE_WAREHOUSE_MANAGER",
  ACCOUNTING = "ROLE_ACCOUNTING",
  MANAGER = "ROLE_MANAGER",
  OTHER = "ROLE_OTHER",
}

export enum AccountRoleForRequest {
  DEPARTMENT = "DEPARTMENT",
  STAFF = "STAFF",
  ADMIN = "ADMIN",
  WAREHOUSE_MANAGER = "WAREHOUSE_MANAGER",
  ACCOUNTING = "ACCOUNTING",
  MANAGER = "MANAGER",
  OTHER = "OTHER",
}

export enum ImportStatus {
  NOT_STARTED = "NOT_STARTED",
  IN_PROGRESS = "IN_PROGRESS",
  COUNTED = "COUNTED",
  COUNT_AGAIN_REQUESTED = "COUNT_AGAIN_REQUESTED",
  CONFIRMED = "CONFIRMED",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  EXTENDED = "EXTENDED",
  READY_TO_STORE = "READY_TO_STORE",
  STORED = "STORED",
}

export enum ExportStatus {
  NOT_STARTED = "NOT_STARTED",
  IN_PROGRESS = "IN_PROGRESS",
  COUNTED = "COUNTED",
  COUNT_CONFIRMED = "COUNT_CONFIRMED",
  WAITING_EXPORT = "WAITING_EXPORT",
  EXTENDED = "EXTENDED",
  CONFIRMED = "CONFIRMED",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

export enum StockcheckStatus {
  NOT_STARTED = "NOT_STARTED",
  IN_PROGRESS = "IN_PROGRESS",
  COUNTED = "COUNTED",
  COUNT_CONFIRMED = "COUNT_CONFIRMED",
  CONFIRMED = "CONFIRMED",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

export enum DetailStatus {
  LACK = "LACK",
  EXCESS = "EXCESS",
  MATCH = "MATCH",
}
